name: Test & Build

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  test_build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run TSC compiler, linters and tests'
        run: |
          npm run typecheck --if-present
          npm run lint --if-present
          npm run test
        env:
          CI: true

      - name: 'Build the artifact'
        run: npm run build
        env:
          CI: true
